package com.lychcs.koikoi.model;

public enum CardID {
    UNKNOWN, // Fallback

    // Spring: Cherry Blossom
    SPRING_YOKAI_RYUMON,
    SPRING_YOKAI_GYORYU,
    SPRING_YOKAI_GENKAKU,
    SPRING_YOKAI_BASAN,

    SPRING_HIKARI_CHERRY_BLOSSOM_STORM,
    SPRING_BEAST_KOI,
    SPRING_BEAST_CRANE,
    SPRING_RIBBON_DEFAULT,
    SPRING_PETAL_DEFAULT,

    // Summer: Lotus
    SUMMER_YOKAI_KOCHOU,
    SUMMER_YOKAI_YUMECHOU,
    SUMMER_YOKAI_UTSUSEMI,
    SUMMER_YOKAI_HIGURASHI,

    SUMMER_HIKARI_GLAZING_SUN,
    SUMMER_BEAST_MOUNTAIN_MONKEY,
    SUMMER_BEAST_SERPENT,
    SUMMER_RIBBON_DEFAULT,
    SUMMER_PETAL_DEFAULT,

    // Autumn: Maple
    AUTUMN_YOKAI_CHOTOTSU,
    AUTUMN_YOKAI_KATAKIRAUWA,
    AUTUMN_YOKAI_KIRIN,
    AUTUMN_YOKAI_HAKUSHIKA,

    AUTUMN_HIKARI_RED_MOON,
    AUTUMN_BEAST_BOAR,
    AUTUMN_BEAST_DEER,
    AUTUMN_RIBBON_DEFAULT,
    AUTUMN_PETAL_DEFAULT,

    // Winter: Pine
    WINTER_YOKAI_TENKO,
    WINTER_YOKAI_KYUBI,
    WINTER_YOKAI_KOTAN,
    WINTER_YOKAI_TATARIMOKKE,

//    WINTER_YAMI_YUKI_ONNA,
    WINTER_HIKARI_POLAR_LIGHT,
    WINTER_BEAST_ARCTIC_FOX,
    WINTER_BEAST_WHITE_OWL,
    WINTER_RIBBON_DEFAULT,
    WINTER_PETAL_DEFAULT
}
