package com.lychcs.koikoi.model;

public enum CardID {
    UNKNOWN, // Fallback für die dynamische Deck-Generierung

    // Spring: Cherry Blossom
    SPRING_OFUDA_GENKAKU,
    SPRING_OFUDA_BASAN,
    SPRING_OFUDA_RYUMON,
    SPRING_OFUDA_GYORYU,

    SPRING_HIKARI_CHERRY_BLOSSOM_STORM,
    SPRING_BEAST_KOI,
    SPRING_BEAST_CRANE,
    SPRING_RIBBON_DEFAULT,
    SPRING_PETAL_DEFAULT,

    // Summer: Lotus
    SUMMER_HIKARI_GLAZING_SUN,
    SUMMER_BEAST_BUTTERFLY,
    SUMMER_BEAST_CICADA,
    SUMMER_RIBBON_DEFAULT,
    SUMMER_PETAL_DEFAULT,

    // Autumn: Maple
    AUTUMN_HIKARI_RED_MOON,
    AUTUMN_BEAST_BOAR,
    AUTUMN_BEAST_DEER,
    AUTUMN_RIBBON_DEFAULT,
    AUTUMN_PETAL_DEFAULT,

    // Winter: Pine
    WINTER_YAMI_YUKI_ONNA,
    WINTER_HIKARI_POLAR_LIGHT,
    WINTER_BEAST_POLAR_FOX,
    WINTER_BEAST_WHITE_OWL,
    WINTER_RIBBON_DEFAULT,
    WINTER_PETAL_DEFAULT
}
