package com.lychcs.koikoi.model;

public enum CardID {
    UNKNOWN, // Fallback

    // Spring: Cherry Blossom
    SPRING_OFUDA_RYUMON,
    SPRING_OFUDA_GYORYU,
    SPRING_OFUDA_GENKAKU,
    SPRING_OFUDA_BASAN,

    SPRING_HIKARI_CHERRY_BLOSSOM_STORM,
    SPRING_BEAST_KOI,
    SPRING_BEAST_CRANE,
    SPRING_RIBBON_DEFAULT,
    SPRING_PETAL_DEFAULT,

    // Summer: Lotus
    SUMMER_OFUDA_KOCHOU,
    SUMMER_OFUDA_YUMECHOU,
    SUMMER_OFUDA_UTSUSEMI,
    SUMMER_OFUDA_HIGURASHI,

    SUMMER_HIKARI_GLAZING_SUN,
    SUMMER_BEAST_BUTTERFLY,
    SUMMER_BEAST_CICADA,
    SUMMER_RIBBON_DEFAULT,
    SUMMER_PETAL_DEFAULT,

    // Autumn: Maple
    AUTUMN_OFUDA_CHOTOTSU,
    AUTUMN_OFUDA_KATAKIRAUWA,
    AUTUMN_OFUDA_KIRIN,
    AUTUMN_OFUDA_HAKUSHIKA,

    AUTUMN_HIKARI_RED_MOON,
    AUTUMN_BEAST_BOAR,
    AUTUMN_BEAST_DEER,
    AUTUMN_RIBBON_DEFAULT,
    AUTUMN_PETAL_DEFAULT,

    // Winter: Pine
    WINTER_OFUDA_TENKO,
    WINTER_OFUDA_KYUBI,
    WINTER_OFUDA_KOTAN,
    WINTER_OFUDA_TATARIMOKKE,

//    WINTER_YAMI_YUKI_ONNA,
    WINTER_HIKARI_POLAR_LIGHT,
    WINTER_BEAST_ARCTIC_FOX,
    WINTER_BEAST_WHITE_OWL,
    WINTER_RIBBON_DEFAULT,
    WINTER_PETAL_DEFAULT
}
